add pages' mobile versions
js-tasks-ru/htmlcss-20230124_lexawin pull request #13
Opened 2023-02-13 21:31 UTC by LexaWin

Мобильные версии страниц

2023-02-13 21:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 06:13 UTC, GSemikozov requested changes

2023-02-14 06:13 UTC, GSemikozov commented on components/preview/preview.css
> +    flex-basis: 164px;
basis тут будет бесполезным

2023-02-14 06:13 UTC, GSemikozov commented on components/preview/preview.css
> +    height: 210px;
и высоту ограничивать тоже не нужно - пусть зависит от внутреннего содержимого

2023-02-14 06:13 UTC, GSemikozov commented on components/container/container.css
> +    max-width: 344px;
на мобильной версии чтобы контент не прилипал к границам вьюпорта достаточно задать контейнеру паддинги слева и справа

2023-02-14 11:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-14 12:02 UTC, GSemikozov approved these changes

2023-02-14 12:02 UTC, merged