add solution for 7-module 1-task
js-tasks-ru/htmlcss-20230124_lexawin pull request #23
Opened 2023-02-19 19:46 UTC by LexaWin

Checkbox

2023-02-19 19:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-19 20:45 UTC, GSemikozov requested changes

2023-02-19 20:45 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  position: absolute;
позиционирование можно задать сразу на .checkbox__icon, а здесь - лишь отображать иконку (display: block;)

2023-02-20 12:31 UTC, GSemikozov approved these changes

2023-02-20 12:31 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-02-20 12:37 UTC, GSemikozov approved these changes

2023-02-20 12:37 UTC, merged

2023-02-20 12:37 UTC, GSemikozov approved these changes

2023-02-20 12:38 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.