add tabs
js-tasks-ru/htmlcss-20230124_lexawin pull request #25
Opened 2023-02-20 20:49 UTC by LexaWin

Add Tabs

2023-02-20 20:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 09:26 UTC, GSemikozov requested changes

2023-02-21 09:26 UTC, GSemikozov commented on index.html
> +                  <h2 class="card__title">Custom form elements</h2>
здесь лучше h3 или даже h4 - h2 как и h1 чаще всего на странице используем 1 раз, либо как заголовки секций верхнего уровня

2023-02-21 10:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 10:33 UTC, GSemikozov approved these changes

2023-02-21 10:33 UTC, merged