add solution for 8-module 1-task
js-tasks-ru/htmlcss-20230124_lexawin pull request #26
Opened 2023-02-21 21:09 UTC by LexaWin

Burger menu

2023-02-21 21:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-22 11:48 UTC, GSemikozov requested changes

2023-02-22 11:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-menu_close {
.burger-menu__close

2023-02-22 11:48 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +      <div class="container">
заворачивать в контейнер и использовать имеющийся блок хедер в данном случае не нужно)

2023-02-22 13:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-22 22:57 UTC, GSemikozov requested changes

2023-02-22 22:57 UTC, GSemikozov commented on 09-lection7/01-burger-menu/index.html
> +          <a href="#" class="menu__item menu__link">Modal</a>
еще такой нюанс - я бы советовал не использовать подход при котором один элемент одновременно является другим - элементы вкладывать друг в друга это ок, но вот использовать на одном уровне... для этого есть модификаторы

2023-02-23 22:41 UTC, GSemikozov approved these changes

2023-02-23 22:41 UTC, merged