add solution for 3-module 1-task
js-tasks-ru/htmlcss-20230124_lexawin pull request #4
Opened 2023-02-01 20:29 UTC by LexaWin

2023-02-01 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-01 20:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-01 21:51 UTC, GSemikozov requested changes

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину не стоит так жестко фиксировать (самый простой вариант когда верстка сломается - более длинный текст)

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает font-family

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
и паддингов

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
pointer-events: none + opacity: 0.5

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  transition: opacity 200ms ease-in-out, background 200ms ease-in-out;
общий для всех типов кнопок транзишн можно задавать сразу на уровне блока

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled {
см выше (фон менять не надо, достаточно полупрозрачности)

2023-02-01 21:51 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled {
везде ниже - по аналогии

2023-02-02 10:46 UTC, LexaWin commented on 03-lection1/01-button/button.css
> +  width: 189px;
Ясно. Значит нужно использовать паддинги?
А высоту можно задавать жестко?

2023-02-02 19:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 10:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
да, паддинги нужно задать. Высоту в случае с кнопкой фиксировать можно

2023-02-03 10:13 UTC, GSemikozov requested changes

2023-02-03 10:13 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  cursor: default;
при pointer-events: none; курсор как раз и будет default, так что можно удалить cursor: default;

2023-02-03 11:13 UTC, GSemikozov approved these changes

2023-02-03 11:14 UTC, merged