add solution for 3-module 2-task
js-tasks-ru/htmlcss-20230124_lexawin pull request #5
Opened 2023-02-02 21:12 UTC by LexaWin

Accordion

2023-02-02 21:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 10:12 UTC, GSemikozov requested changes

2023-02-03 10:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  На макете отступ слева 32px,
контентом может быть все что угодно, поэтому - лучше создать элемент .accordion__content, и уже в него вкладывать список

2023-02-03 10:12 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 50px 24px 32px;
паддинги лучше один раз задать на уровне .accordion__item

2023-02-03 11:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-03 11:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 11:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-03 13:53 UTC, GSemikozov approved these changes

2023-02-03 13:53 UTC, merged