add solution for 4-module 2-task
js-tasks-ru/htmlcss-20230124_lexawin pull request #7
Opened 2023-02-06 19:22 UTC by LexaWin

Skeleton

2023-02-06 19:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-07 10:01 UTC, GSemikozov requested changes

2023-02-07 10:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  justify-content: space-evenly;
здесь лучше вертикальное центрирование использовать

2023-02-07 10:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
лишнее, блочный элемент и так растягивается на 100%

2023-02-07 10:51 UTC, LexaWin commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 100%;
Здесь явно ширину задал, чтобы ширина полосок считалась от нее. Я вычитал, что проценыт берутся от такого же параметра родителя.
Это лишнее? Просто у полосок есть свои контейнеры, не будет тогда ширина растчитываться от ширины контейнера?

2023-02-07 10:51 UTC, LexaWin commented on 04-lection2/02-skeleton/skeleton.css
> +  justify-content: space-evenly;
Здесь не понял. Можешь пояснить, что за вертикальное центрирование?

2023-02-09 19:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-09 19:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 09:55 UTC, GSemikozov approved these changes

2023-02-10 09:55 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-02-10 09:56 UTC, GSemikozov approved these changes

2023-02-10 09:56 UTC, merged