add component page
js-tasks-ru/htmlcss-20230124_lexawin pull request #9
Opened 2023-02-09 21:12 UTC by LexaWin

Component Page

2023-02-09 21:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-10 10:03 UTC, GSemikozov requested changes

2023-02-10 10:03 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page {
блок page у нас уже есть, поэтому - тут через подификатор, например .page_inner

2023-02-10 10:03 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__header {
у нас уже есть хедер, используем его

2023-02-10 10:03 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__footer {
используем уже имеющийся футер

2023-02-10 10:03 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__inner {
это самостоятельный блок, я бы предложил реализовать его отдельно. Высоту на 100% растягивать не нужно

2023-02-10 10:03 UTC, GSemikozov commented on components/component/component.css
> +.component {
компонент с названием Компонент - не очень хорошая практика :) предлагаю переименовать хотя бы в component-description

2023-02-10 10:03 UTC, GSemikozov commented on pages/tepmlate.html
> +                <li class="menu__item">Modal</li>
1. реализовывать через список не обязательно + более правильно с точки зрения семантики использовать nav + a

2023-02-10 10:03 UTC, GSemikozov commented on pages/tepmlate.html
> +                <li class="menu__item">Modal</li>
2. в каждом `<li>` должна быть ссылка `<a>`

2023-02-10 11:11 UTC, LexaWin commented on components/component-page/component-page.css
> +.component-page {
Тут не понял. Для страницы компонента не нужно создавать отдельный блок?
Просто блок `page` у нас сверстан на флексах. А страницу компонента мы верстали на гридах. Я поэтому и создал для страницы компонента отдельный блок `component-page`.

2023-02-10 11:11 UTC, LexaWin commented on components/component-page/component-page.css
> +.component-page__header {
Я использую блок `header`, а под `component-page__header` примиксовываю ему изменения в стиле, ведь на странице компонента у `header` другая высота и еще убираю у него паддинги.

2023-02-10 11:11 UTC, LexaWin commented on components/component-page/component-page.css
> +.component-page__inner {
Если не растягивать высоту, то он подстраивается под высоту меню.

2023-02-10 11:11 UTC, LexaWin commented on components/component-page/component-page.css
> +.component-page__footer {
Я использую блок `footer`, а под `component-page__footer` примиксовываю ему изменения в стиле, ведь на странице компонента у `footer` другие паддинги.

2023-02-10 11:16 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page {
нет, не надо:
```
.page_inner {
   /* все стили которые нужны */
}
```

2023-02-10 11:18 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__header {
этого не нужно делать, тем более фиксировать высоту - в полном макете страницы видно, что у хедера прозрачный фон, паддинги остаются, заголовок не используется:
<img width="782" alt="Screenshot 2023-02-10 at 13 17 18" src="https://user-images.githubusercontent.com/6191270/218079292-d0e343f1-2c34-47a4-b3b9-8b90b7606750.png">

2023-02-10 11:18 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__footer {
см выше - та же история что и с хедером

2023-02-10 11:19 UTC, GSemikozov commented on components/component-page/component-page.css
> +.component-page__inner {
да, это нормально - сейчас внутри нет контента, но он там обязательно будет, и уже этот внутренний контент и будет определять высоту

2023-02-10 16:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-11 11:10 UTC, GSemikozov requested changes

2023-02-11 11:10 UTC, GSemikozov commented on components/container/container.css
> +  height: 100%;
вот этого делать не нужно (высота контейнера всегда будет зависеть только от внутреннего содержимого). Если нужно добавить высоту в конкретном контексте - то через класс-микс

2023-02-11 13:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-12 12:25 UTC, GSemikozov requested changes

2023-02-12 12:25 UTC, GSemikozov commented on pages/tepmlate.html
> +      <div class="header"></div>
семантическую разметку тоже желательно использовать - header

2023-02-12 12:25 UTC, GSemikozov commented on pages/tepmlate.html
> +      <div class="main">
main

2023-02-12 12:25 UTC, GSemikozov commented on pages/tepmlate.html
> +              <h1 class="component-description__header">Histogram</h1>
h3-h4

2023-02-12 12:25 UTC, GSemikozov commented on pages/tepmlate.html
> +      <div class="footer footer_transparent">
footer

2023-02-13 10:35 UTC, GSemikozov approved these changes

2023-02-13 10:35 UTC, merged